### PR TITLE
[FEAT] Added progress bar

### PR DESCRIPTION
**Pull request by ryuvi**
Hi, I found your code and found it awesome. As I used others downloaders and the experience with a progress bar showing the progress of the download was useful, I implemented it on your code, hope you like the result.

### CODE REVIEW

**Comment by RonStrauss** [comment]
I've implemented these changes locally, but noticed that it adds the progress bar only for the file write process.
Ideally, it would go together with the `request`  module. I'd be happy to help if you would like.

**Comment by ryuvi** [comment]
No problem, implemented the progress bar for the requests download queue, and also I had a issue with the folder creation in windows, because of some characters that is not allowed, so I made a regex to deal with it.

**Comment by RonStrauss** [comment]
I've also ran into this problem and made a pr for the same issue 😅
I look forward to seeing which pr would get implemented.
Care to offer your insight regarding #3 ? You've mentioned youve tried other libraries, how do they address this kind of issue, if at all?

**Comment by M4p4** [comment]
I added a progressbar to the project. Please update the repo.

**Pull request closed without merging**
