### PR TITLE
[FEAT] Implement retry logic, slight cleanup

### PR DESCRIPTION
**Pull request by RonStrauss**
I've gone ahead and implemented the retry logic.

It's behind an optional flag, as to not break existing behavior.

Tried to do a slight cleanup of the code as well.

### CODE REVIEW

**Comment by RonStrauss** [comment]
Sorry, I've made some more tests, and I'm sometimes getting 416 (invalid range). gonna close it for now.

**Comment by RonStrauss** [comment]
Made some cleanup, and refactored the logic. let me know what you think @M4p4

**Comment by M4p4** [comment]
Hi @RonStrauss , i looked at your code and decide to do a different approach. I was not able to reproduce a failed download but I added a retries loop with 3 attempts max.
Moving `user_agent` and `host` in constants is a good idea, also thanks for spotting my typo with the progressbar unit.

**Comment by M4p4** [comment]
@RonStrauss I rewrote the whole script now. 
I added following features for you:
- download files simultaneously
- detect if file not fully downloaded and redownload

I wish you good weekend and hope you like the changes.

**Comment by RonStrauss** [comment]
@M4p4 Thank you for taking the time to look at my code and add new features. 
Python isn't my day-to-day language - so I'm assuming my code is atrocious, I'm happy you were able to extract the useful parts, haha.
It was unfortunate you couldn't reproduce the issue I'm having, but at least now I have a version of my own to use 😅
I wanted to have a single run to take care of all of the links, without having to re-call the python script after it ends, which is why i'll be sticking to my version for the time being. The mid-way stops are pretty frequent.
Have a wonderful weekend 👍

**Pull request closed without merging**
